apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 8000 # Port exposed by the service
      targetPort: 8000 # Port on which the FastAPI app is running in the container
  type: LoadBalancer  # This works with Docker Desktop